import json
import shutil
import zipfile
from pathlib import Path

from app.core import storage
from app.core.storage_backend import get_backend
from app.models.annotation import Annotation
from app.models.image import Image
from app.models.label import Label

# Every Nth image goes to the validation set, i.e. a 20% val / 80% train split.
_VAL_STRIDE = 5


def _yaml_quote(value: str) -> str:
    """Render a string as a double-quoted YAML scalar.

    Label names are user input, so they can contain the characters that give
    YAML meaning — ``:``, ``#``, quotes, leading digits. Quoting and escaping
    keeps ``data.yaml`` parseable whatever the user named a class, instead of
    emitting a file that a trainer refuses to load.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _split_train_val(names: list[str]) -> tuple[list[str], list[str]]:
    """Split exported image filenames into (train, val) deterministically.

    The project has no split mechanism of its own, so this defines one. It is
    deterministic by construction: membership depends only on an image's
    position in the project's image order, never on a random seed or the clock,
    so re-exporting the same project twice yields byte-identical manifests.

    Taking every 5th image gives exactly the intended 80/20 for any dataset of
    five or more. Two guards cover datasets too small for that to work:

    * Under 5 images the stride selects nothing, which would ship an **empty**
      validation set and a dataset no trainer can validate against, so the last
      image is used instead.
    * A single image cannot be split at all, so it is listed in both manifests.
      A duplicate is the lesser evil versus an empty train or val set, and a
      one-image project is only ever a pipeline smoke test.
    """
    if not names:
        return [], []
    if len(names) == 1:
        # Deliberately the same image in both — see the docstring.
        return list(names), list(names)

    val = [
        name
        for idx, name in enumerate(names)
        if idx % _VAL_STRIDE == _VAL_STRIDE - 1
    ]
    if not val:
        val = [names[-1]]
    in_val = set(val)
    train = [name for name in names if name not in in_val]
    return train, val


def _unique_export_name(used_stems: set[str], filename: str) -> str:
    """Pick a collision-free export filename, preserving the extension.

    Two images can share a stem (``cat.jpg`` and ``cat.png``), which would make
    one overwrite the other inside the archive. Mutates ``used_stems``.

    The YOLO exporter keeps its own copy of this loop inline: it is verified,
    released behavior, and swapping it for this helper would mean editing a
    working code path for no functional gain.
    """
    suffix = Path(filename).suffix
    stem = Path(filename).stem
    unique = stem
    counter = 1
    while unique in used_stems:
        unique = f"{stem}_{counter}"
        counter += 1
    used_stems.add(unique)
    return f"{unique}{suffix}"


class ExportManager:
    """Generates dataset exports from persisted annotations."""

    def _yolo_class_index(self, labels: list[Label]) -> dict[str, int]:
        """Map label id -> class index (order = labels.json order)."""
        return {label.id: idx for idx, label in enumerate(labels)}

    def _write_data_yaml(
        self,
        build_dir: Path,
        labels: list[Label],
        train: list[str],
        val: list[str],
    ) -> None:
        """Write the Ultralytics-style ``data.yaml`` plus the split manifests.

        ``train``/``val`` point at text files listing one image path per line
        rather than at separate ``images/train`` and ``images/val`` folders.
        That keeps the archive's flat ``images/`` + ``labels/`` layout — and so
        every existing consumer of this export — working unchanged, while still
        describing a real split. Trainers locate each label file by swapping
        ``/images/`` for ``/labels/`` in these paths, which the shared stem
        guarantees.
        """
        (build_dir / "train.txt").write_text(
            "".join(f"./images/{name}\n" for name in train), encoding="utf-8"
        )
        (build_dir / "val.txt").write_text(
            "".join(f"./images/{name}\n" for name in val), encoding="utf-8"
        )

        if labels:
            names_block = "\n".join(
                f"  {idx}: {_yaml_quote(label.name)}"
                for idx, label in enumerate(labels)
            )
        else:
            # An empty mapping still has to be valid YAML.
            names_block = "  {}"

        (build_dir / "data.yaml").write_text(
            "# YOLO dataset configuration generated by ForgoteLabeling.\n"
            "#\n"
            "# `path` is this dataset's root, written relative to this file so the\n"
            "# extracted folder is self-contained and movable. Some trainers\n"
            "# resolve a relative root against their own datasets directory\n"
            "# instead; if yours does, set `path` to the absolute path of the\n"
            "# folder holding this file.\n"
            "#\n"
            "# `train`/`val` list image paths, one per line. Each label file is\n"
            "# the matching name under labels/ with a .txt extension.\n"
            f"path: .\n"
            f"train: train.txt\n"
            f"val: val.txt\n"
            f"nc: {len(labels)}\n"
            "names:\n"
            f"{names_block}\n",
            encoding="utf-8",
        )

    def export_yolo(
        self,
        project_id: str,
        images: list[Image],
        annotations: list[Annotation],
        labels: list[Label],
    ) -> Path:
        """Build a YOLO-format dataset and return the path to a zip archive.

        Archive layout:
            dataset/
                images/
                labels/
                classes.txt
                data.yaml
                train.txt
                val.txt
        """
        export_root = storage.export_dir(project_id)
        build_dir = export_root / "dataset"

        # Start clean so stale files never leak into a new export.
        if build_dir.exists():
            shutil.rmtree(build_dir)
        images_out = build_dir / "images"
        labels_out = build_dir / "labels"
        images_out.mkdir(parents=True, exist_ok=True)
        labels_out.mkdir(parents=True, exist_ok=True)

        class_index = self._yolo_class_index(labels)
        backend = get_backend()

        # classes.txt (one class name per line, ordered by index).
        classes_file = build_dir / "classes.txt"
        classes_file.write_text(
            "\n".join(label.name for label in labels) + ("\n" if labels else ""),
            encoding="utf-8",
        )

        annotations_by_image: dict[str, list[Annotation]] = {}
        for ann in annotations:
            annotations_by_image.setdefault(ann.image_id, []).append(ann)

        # Boxes that cannot be represented as a YOLO class (no label, or a
        # label id that no label owns) are recorded here so they are surfaced
        # explicitly in the export instead of silently vanishing.
        skipped: list[str] = []

        # YOLO pairs each image with its label file by a shared stem. Uploads
        # keep full filenames unique, but two images can still share a stem
        # (e.g. cat.jpg and cat.png both map to cat.txt), which would overwrite
        # one label file and silently drop its annotations. Track used stems and
        # disambiguate on collision so the image copy and its label file always
        # stay paired and no annotations are lost. In the common (no-collision)
        # case the export names are byte-identical to before.
        used_stems: set[str] = set()

        # Image filenames actually written into the archive, in project order.
        # The split is built from this rather than from ``images`` so a manifest
        # can never reference a file the archive does not contain (an image
        # whose bytes are missing is skipped below), which would fail training
        # at load time.
        exported_names: list[str] = []

        for image in images:
            suffix = Path(image.filename).suffix

            stem = Path(image.filename).stem
            unique_stem = stem
            counter = 1
            while unique_stem in used_stems:
                unique_stem = f"{stem}_{counter}"
                counter += 1
            used_stems.add(unique_stem)

            # Read the image through the storage backend so the export works
            # the same whether bytes live on the local disk (v1.0.0) or in cloud
            # object storage. Missing images are skipped, exactly as before.
            data = backend.read_image_bytes(project_id, image.filename)
            if data is not None:
                (images_out / f"{unique_stem}{suffix}").write_bytes(data)
                exported_names.append(f"{unique_stem}{suffix}")

            # One label file per image (empty file if no boxes).
            label_lines: list[str] = []
            skipped_here = 0
            for ann in annotations_by_image.get(image.id, []):
                cls = class_index.get(ann.label_id)
                if cls is None:
                    # Orphan/unlabeled box: keep it out of the YOLO label file
                    # (it has no valid class) but count it for the report.
                    skipped_here += 1
                    continue
                # Convert top-left normalized box -> YOLO center format.
                cx = ann.x + ann.width / 2
                cy = ann.y + ann.height / 2
                label_lines.append(
                    f"{cls} {cx:.6f} {cy:.6f} {ann.width:.6f} {ann.height:.6f}"
                )

            if skipped_here:
                skipped.append(f"{image.filename}\t{skipped_here}")

            label_name = unique_stem + ".txt"
            (labels_out / label_name).write_text(
                "\n".join(label_lines) + ("\n" if label_lines else ""),
                encoding="utf-8",
            )

        # Only write the report when something was skipped, so a fully-labeled
        # dataset still exports a pristine, standard YOLO structure.
        if skipped:
            total = sum(int(line.split("\t")[1]) for line in skipped)
            (build_dir / "unlabeled.txt").write_text(
                "# Annotations omitted from this YOLO export because they have "
                "no label or reference a label that no longer exists.\n"
                "# These boxes were NOT dropped from the project; assign a "
                "valid label to include them.\n"
                "# Format: <image_filename><TAB><skipped_count>\n"
                + "\n".join(skipped)
                + f"\n# total_skipped\t{total}\n",
                encoding="utf-8",
            )

        # data.yaml + the train/val manifests describing the split.
        train, val = _split_train_val(exported_names)
        self._write_data_yaml(build_dir, labels, train, val)

        zip_path = export_root / "dataset_yolo.zip"
        if zip_path.exists():
            zip_path.unlink()

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file in build_dir.rglob("*"):
                if file.is_file():
                    zf.write(file, file.relative_to(export_root))

        return zip_path

    # -- COCO -----------------------------------------------------------------
    def _image_size(self, image: Image, data: bytes | None) -> tuple[int, int]:
        """Best-effort pixel dimensions for an image.

        COCO stores absolute pixel geometry while this app stores normalized
        boxes, so real dimensions are required to denormalize. ``Image.width`` /
        ``Image.height`` are filled in at upload time; the Pillow fallback
        covers rows written before that existed (or by an install without
        Pillow) and costs nothing extra because the bytes are already in memory
        for the archive copy.
        """
        if image.width and image.height:
            return int(image.width), int(image.height)
        if data is not None:
            try:
                from io import BytesIO

                from PIL import Image as PILImage

                with PILImage.open(BytesIO(data)) as im:
                    return int(im.size[0]), int(im.size[1])
            except Exception:
                pass
        return 0, 0

    def export_coco(
        self,
        project_id: str,
        images: list[Image],
        annotations: list[Annotation],
        labels: list[Label],
    ) -> Path:
        """Build a COCO-format dataset and return the path to a zip archive.

        Archive layout:
            dataset/
                images/
                annotations/
                    instances.json

        Built under its own ``coco/`` scratch directory so a COCO export can
        never race with, or be cleaned up by, a YOLO export of the same project;
        the archive paths still start at ``dataset/`` because the zip arcnames
        are taken relative to that scratch root.
        """
        export_root = storage.export_dir(project_id) / "coco"
        build_dir = export_root / "dataset"

        # Start clean so stale files never leak into a new export.
        if build_dir.exists():
            shutil.rmtree(build_dir)
        images_out = build_dir / "images"
        annotations_out = build_dir / "annotations"
        images_out.mkdir(parents=True, exist_ok=True)
        annotations_out.mkdir(parents=True, exist_ok=True)

        backend = get_backend()

        # COCO category ids are conventionally 1-based (0 is reserved for
        # background by many tools), unlike YOLO's 0-based class indices. Order
        # still follows labels.json, so category N here is YOLO class N-1.
        category_id = {label.id: idx + 1 for idx, label in enumerate(labels)}
        categories = [
            {"id": idx + 1, "name": label.name, "supercategory": ""}
            for idx, label in enumerate(labels)
        ]

        annotations_by_image: dict[str, list[Annotation]] = {}
        for ann in annotations:
            annotations_by_image.setdefault(ann.image_id, []).append(ann)

        coco_images: list[dict] = []
        coco_annotations: list[dict] = []
        used_stems: set[str] = set()
        next_image_id = 1
        next_annotation_id = 1

        for image in images:
            # Read through the storage backend so this works identically on the
            # local disk and on cloud object storage. Missing images are skipped.
            data = backend.read_image_bytes(project_id, image.filename)
            if data is None:
                continue

            file_name = _unique_export_name(used_stems, image.filename)
            (images_out / file_name).write_bytes(data)

            width, height = self._image_size(image, data)
            image_id = next_image_id
            next_image_id += 1
            coco_images.append(
                {
                    "id": image_id,
                    "file_name": file_name,
                    "width": width,
                    "height": height,
                }
            )

            # Without real dimensions a pixel bbox cannot be computed, so the
            # image is still listed (it is in the archive) but its boxes are
            # left out rather than written as meaningless zeros.
            if not width or not height:
                continue

            for ann in annotations_by_image.get(image.id, []):
                category = category_id.get(ann.label_id)
                if category is None:
                    # Same rule as the YOLO export: a box with no label, or one
                    # referencing a deleted label, has no category to belong to.
                    continue
                # Normalized top-left box -> absolute pixel [x, y, w, h].
                box_w = ann.width * width
                box_h = ann.height * height
                coco_annotations.append(
                    {
                        "id": next_annotation_id,
                        "image_id": image_id,
                        "category_id": category,
                        "bbox": [
                            round(ann.x * width, 2),
                            round(ann.y * height, 2),
                            round(box_w, 2),
                            round(box_h, 2),
                        ],
                        "area": round(box_w * box_h, 2),
                        "iscrowd": 0,
                    }
                )
                next_annotation_id += 1

        (annotations_out / "instances.json").write_text(
            json.dumps(
                {
                    "images": coco_images,
                    "annotations": coco_annotations,
                    "categories": categories,
                },
                indent=2,
            ),
            encoding="utf-8",
        )

        zip_path = export_root / "dataset_coco.zip"
        if zip_path.exists():
            zip_path.unlink()

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file in build_dir.rglob("*"):
                if file.is_file():
                    zf.write(file, file.relative_to(export_root))

        return zip_path


manager = ExportManager()
